export interface Benefit {
  id: string;
  name: string;
  documents: string[];
}

export interface RuralProof {
  id: string;
  name: string;
}

export const benefits: Benefit[] = [
  {
    id: "bpc-deficiente",
    name: "BPC ao Deficiente",
    documents: [
      "RG (validade de 10 anos)",
      "CPF",
      "Senha do Meu INSS",
      "Comprovante Biométrico (CIN, Título de Eleitor ou CNH)",
      "Cadastro no CRAS (Folha V7)",
      "Termo de Representação",
      "Procuração Administrativa",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Termo de Responsabilidade",
      "Separação de Fato",
      "Certidão de Nascimento ou Casamento",
      "Carteira de Trabalho",
      "Comprovante de Residência (No nome do requerente ou responsável legal) ou Declaração de Residência",
      "Localização Atual",
      "RG e CPF do Rogado",
      "RG do Irmão",
      "CPF do Irmão",
      "Certidão de Nascimento ou Casamento do Irmão",
      "Carteira de Trabalho do Irmão",
      "RG da Irmã",
      "CPF da Irmã",
      "Certidão de Nascimento ou Casamento da Irmã",
      "Carteira de Trabalho da Irmã",
      "RG do Pai",
      "CPF do Pai",
      "Certidão de Nascimento ou Casamento do Pai",
      "Carteira de Trabalho do Pai",
      "RG da Mãe",
      "CPF da Mãe",
      "Certidão de Nascimento ou Casamento da Mãe",
      "Carteira de Trabalho da Mãe",
      "Receitas Médicas",
      "Exames",
      "Laudos Médicos",
      "Outros Documentos Médicos",
      "Fotos da Casa (Casa, Faixada, Rua)",
    ],
  },
  {
    id: "bpc-idoso",
    name: "BPC ao Idoso",
    documents: [
      "RG (validade de 10 anos)",
      "CPF",
      "Senha do Meu INSS",
      "Comprovante Biométrico (CIN, Título de Eleitor ou CNH)",
      "Cadastro no CRAS (Folha V7)",
      "Termo de Representação",
      "Procuração Administrativa",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Separação de Fato",
      "Termo de Responsabilidade",
      "Certidão de Nascimento ou Casamento",
      "Carteira de Trabalho",
      "Comprovante de Residência",
      "Localização Atual",
      "Receitas Médicas",
      "Exames",
      "Laudos Médicos",
      "Fotos da Casa (Casa, Faixada, Rua)",
      "Outros Documentos Médicos",
    ],
  },
  {
    id: "beneficio-incapacidade",
    name: "Benefício por Incapacidade",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Declaração de Escolaridade",
      "Termo de Responsabilidade",
      "Separação de Fato",
      "RG",
      "CPF",
      "Certidão de Nascimento ou Casamento",
      "Carteira de Trabalho",
      "Comprovante de Residência",
      "Receitas Médicas",
      "Exames",
      "Laudos Médicos",
      "Outros Documentos Médicos",
    ],
  },
  // {
  //   id: "aposentadoria-rural",
  //   name: "Aposentadoria Rural",
  //   documents: [
  //     "Termo de Representação",
  //     "Procuração Administrativa",
  //     "Procuração Judicial e Declaração de Hipossuficiência",
  //     "Contrato de Honorários",
  //     "Senha do Meu INSS",
  //     "Termo de Responsabilidade",
  //     "RG",
  //     "CPF",
  //     "Certidão de Nascimento ou Casamento",
  //     "Carteira de Trabalho",
  //     "Comprovante de Residência",
  //     "INCRA",
  //     "ITR",
  //     "Escritura Pública",
  //     "Certidão de Casamento do Pai",
  //     "Certidões de Nascimento dos Irmãos",
  //     "Certidão de Alistamento Militar da Parte Autora",
  //     "Certidão da Justiça Eleitoral com Indicação do Exercício de Atividade Rural",
  //     "Ficha de Sindicato Rural",
  //     "Carteira de Filiação ao Sindicato Rural",
  //     "Recibos de Pagamento do Sindicato Rural",
  //     "Ficha de Cadastramento Familiar Realizado pela Secretaria da Saúde do Município",
  //     "Prontuário Médico do Posto de Saúde",
  //     "Blocos de Notas do Produtor Rural",
  //     "Carteira de Vacinação dos Filhos",
  //     "Ficha de Inscrição na Escola Situada na Área Rural",
  //     "Declaração Anual do Produtor",
  //     "Ficha de Crediário de Estabelecimentos Locais da Área Rural",
  //     "Recibos de Compra de Implementos ou Insumos Agrícolas",
  //   ],
  // },
  {
    id: "aposentadoria-idade-tempo",
    name: "Aposentadoria por Idade / Tempo de Contribuição",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa (anexar a OAB do advogado em PDF)",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG",
      "CPF",
      "Certidão de Nascimento ou Casamento",
      "Comprovante de Residência",
      "Carteiras de Trabalho",
      "CTC (Certidão do Tempo de Contribuição de Outro Regime)",
      "Carnês de Contribuição",
      "Sentença de Processos Trabalhistas para Averbação do CNIS para Vínculos não Registrados no INSS",
      "Extratos do FGTS",
      "Contracheques",
      "Declaração da Instituição de Ensino do Período de Contrato e Atividade Exclusiva de Magistério",
      "Diploma ou Documento do Conselho Representativo da Profissão de que está Habilitado para Exercer a Função",
    ],
  },
  {
    id: "aposentadoria-especial",
    name: "Aposentadoria Especial",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa (anexar a OAB do advogado em PDF)",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG",
      "CPF",
      "Certidão de Nascimento ou Casamento",
      "Comprovante de Residência",
      "Carteiras de Trabalho",
      "CTC (Certidão do Tempo de Contribuição de Outro Regime)",
      "Carnês de Contribuição",
      "Sentença de Processos Trabalhistas para Averbação do CNIS para Vínculos não Registrados no INSS",
      "Extratos do FGTS",
      "Contracheques",
      "PPP (Perfil Profissiográfico Previdenciário)",
      "LTCAT (Laudo Técnico de Condições Ambientais do Trabalho)",
      "PPRA (Programa de Prevenção de Riscos Ambientais)",
      "PGR (Programa de Gerenciamento de Riscos)",
      "PCMAT (Programa de Condições e Meio Ambiente de Trabalho na Indústria da Construção)",
      "CAT (Comunicação de Acidente do Trabalho)",
    ],
  },
  {
    id: "aposentadoria-deficiente",
    name: "Aposentadoria por Tempo de Contribuição ou Idade ao Deficiente",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa (anexar a OAB do advogado em PDF)",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG",
      "CPF",
      "Certidão de Nascimento ou Casamento",
      "Comprovante de Residência",
      "Carteiras de Trabalho",
      "CTC (Certidão do Tempo de Contribuição de Outro Regime)",
      "Carnês de Contribuição",
      "Receitas Médicas",
      "Exames",
      "Laudos e Atestados Médicos",
      "Outros Documentos Médicos",
    ],
  },
  {
    id: "pensao-morte",
    name: "Pensão por Morte",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa (anexar a OAB do advogado em PDF)",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG (Requerente)",
      "CPF (Requerente)",
      "Certidão de Nascimento ou Casamento (Requerente)",
      "Comprovante de Residência",
      "RG (Falecido)",
      "CPF (Falecido)",
      "Certidão de Nascimento ou Casamento (Falecido)",
      "Carteira de Trabalho e GPS (Falecido)",
      "Certidão de Óbito",
      "Certidão de Nascimento de Filho Havido em Comum",
      "Certidão de Casamento Religioso",
      "Declaração do Imposto de Renda do Segurado (em que conste o interessado como seu dependente)",
      "CadÚnico",
      "Disposições Testamentárias",
      "Declaração Especial Feita Perante Tabelião",
      "Prova de Mesmo Domicílio",
      "Prova de Encargos Domésticos Evidentes e Existência de Sociedade ou Comunhão nos Atos da Vida Civil",
      "Procuração ou Fiança Reciprocamente Outorgada",
      "Conta Bancária Conjunta",
      "Registro em Associação onde Conste como Dependente",
      "Ficha ou Livro de Registro de Empregados",
      "Apólice de Seguro Pessoa Interessada como sua Beneficiária",
      "Ficha de Tratamento em Instituição de Assistência Médica (da qual conste o segurado como responsável)",
      "Escritura de Compra e Venda de Imóvel - Dependente",
      "Declaração de Não Emancipação do Dependente Menor de 21 Anos",
      "Quaisquer Outros que Possam Levar à Convicção do Fato a Comprovar",
    ],
  },
  {
    id: "auxilio-reclusao",
    name: "Auxílio Reclusão",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa (anexar a OAB do advogado em PDF)",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG (Requerente)",
      "CPF (Requerente)",
      "Certidão de Nascimento ou Casamento (Requerente)",
      "Comprovante de Residência",
      "RG (Recluso)",
      "CPF (Recluso)",
      "Certidão de Nascimento ou Casamento (Recluso)",
      "Carteira de Trabalho e GPS (Recluso)",
      "CTC (Certidão do Tempo de Contribuição de Outro Regime)",
      "Declaração Expedida pela Autoridade Carcerária Informando a Data da Prisão e o Regime",
    ],
  },
  {
    id: "salario-maternidade",
    name: "Salário Maternidade",
    documents: [
      "Termo de Representação",
      "Procuração Administrativa",
      "Procuração Judicial e Declaração de Hipossuficiência",
      "Contrato de Honorários",
      "Senha do Meu INSS",
      "Petição Dirigida ao INSS",
      "Termo de Responsabilidade",
      "RG",
      "CPF",
      "Certidão de Nascimento ou Casamento",
      "Comprovante de Residência",
      "Carteira de Trabalho",
      "Certidão de Nascimento do Bebê",
      "Em caso de guarda, deve apresentar o Termo de Guarda com a indicação de que a guarda destina-se à adoção",
      "Em caso de adoção, deverá apresentar a nova Certidão de Nascimento expedida após a decisão judicial",
      "Pagamento de uma GPS (Indicar qual modalidade de contribuição)"
    ],
  },
  {
    id: "guarda-curatela",
    name: "Guarda / Curatela",
    documents: [
      "RG e CPF (AUTOR)",
      "Certidão de Nascimento ou Casamento (AUTOR)",
      "Carteira de Trabalho Física ou Digital (AUTOR)",
      "Comprovante de Residência (AUTOR)",
      "Antecedentes Criminais - Federal e Estadual (AUTOR)",
      "Declaração de Indoneidade Moral (AUTOR)",
      "Laudo Médico de Sanidade Mental (AUTOR)",
      "RG e CPF (MENOR/CURATELADO)",
      "Certidão de Nascimento ou Casamento (MENOR/CURATELADO)",
      "Carteira de Trabalho Física ou Digital (MENOR/CURATELADO)",
      "Comprovante de Residência (MENOR/CURATELADO)",
      "Certidão de Nada Consta do Cartório de Bens e Imóveis (MENOR/CURATELADO)",
      "Laudo Médico (atestando a incapacidade física e mental do curatelado)",
      "Termo de Anuência (DOS PAIS)"
    ],
  },
  {
    id: "ação-trabalhista",
    name: "Ação Trabalhista",
    documents: [
      "RG e CPF (AUTOR)",
      "Certidão de Nascimento ou Casamento (AUTOR)",
      "Carteira de Trabalho Física ou Digital (AUTOR)",
      "Comprovante de Residência",
      "Dados do Reclamado (Nome, CPF, CNPJ, Endereço, etc.)",
      "Termo de Recisão",
      "Extrato FGTS",
      "Provas do Vínculo Trabalhista",
      "Comprovante de Pagamentos (Extratos Bancários, Recibos, etc.)",
      "Farda",
      "Fotos Trabalhando ou em Confraternização da Empresa",
      "Prints",
      "Três Testemunhas (RG, CPF, Comprovante de Residência)",
      "Provas do Ocorrido (Fotos, Vídeos, Laudos Médicos, etc.)",
    ]
  },
  {
    id: "ação-civil",
    name: "Ação Civil",
    documents: [
      "RG e CPF (AUTOR)",
      "Certidão de Nascimento ou Casamento (AUTOR)",
      "Carteira de Trabalho Física ou Digital (AUTOR)",
      "Comprovante de Residência",
      "Dados do Réu (Nome, CPF, CNPJ, Endereço, etc.)",
      "Provas do Direito Alegado (Fotos, Vídeos, Laudos Médicos, etc.)",
      "Três Testemunhas (RG, CPF, Comprovante de Residência)",
    ]
  }
];

export const ruralProofs: RuralProof[] = [
  { id: "certidao-incra", name: "INCRA" },
  { id: "carne-segurado-especial", name: "Carnê de Contribuição como Segurado Especial" },
  { id: "certidao-itr", name: "ITR" },
  { id: "escritura-publica", name: "Escritura Pública" },
  { id: "documento-terra", name: "Documento da Terra" },
  { id: "documento-proprietario-terra", name: "Documento do Proprietário da Terra" },
  { id: "documento-arrendatario-terra", name: "Documento do Arrendatário da Terra" },
  { id: "caf-dap", name: "CAF ou DAP" },
  { id: "frentes-produtivas", name: "Programa de Frentes Produtivas" },
  { id: "matricula-propriedade", name: "Matrícula de Propriedade Rural" },
  { id: "certidao-registro-imovel", name: "Certidão de Registro de Imóvel Rural" },
  { id: "escritura-propriedade", name: "Escritura de Propriedade Rural" },
  { id: "certidao-casamento-pai", name: "Certidão de Casamento do Pai" },
  { id: "certidoes-nascimento-irmaos", name: "Certidões de Nascimento dos Irmãos" },
  { id: "certidao-alistamento-militar", name: "Certidão de Alistamento Militar da Parte Autora" },
  { id: "certidao-justica-eleitoral", name: "Certidão da Justiça Eleitoral com Indicação do Exercício de Atividade Rural" },
  { id: "folha-pagamento-seca", name: "Folha de Pagamento do Programa Permanente de Combate a Seca" },
  { id: "ficha-sindicato-rural", name: "Ficha de Sindicato Rural" },
  { id: "carteira-filiacao-sindicato", name: "Carteira de Filiação ao Sindicato Rural" },
  { id: "recibos-sindicato", name: "Recibos de Pagamento do Sindicato Rural" },
  { id: "ficha-cadastramento-saude", name: "Ficha de postinho de saúde/secretaria de saúde" },
  { id: "prontuario-medico", name: "Prontuário Médico do Posto de Saúde" },
  { id: "blocos-notas-produtor", name: "Blocos de Notas do Produtor Rural" },
  { id: "carteira-vacinacao-filhos", name: "Carteira de Vacinação dos Filhos" },
  { id: "contratos-arrendamentos", name: "Contratos de Arrendamentos" },
  { id: "ficha-vacinacao-filhos", name: "Carteira de Vacinação dos Filhos" },
  { id: "ficha-inscricao-escola-rural", name: "Ficha de Matrícula da Escola Rural (orienta-se pegar uma declaração junto ao documento)" },
  { id: "ficha-inscricao-escola-filho", name: "Ficha de Matrícula dos Filhos (orienta-se a pegar uma declaração junto ao documento)" },
  { id: "declaracao-anual-produtor", name: "Declaração Anual do Produtor" },
  { id: "ficha-crediario-rural", name: "Ficha de Crediário de Estabelecimentos Locais da Área Rural" },
  { id: "recibos-implementos-agricolas", name: "Recibos de Compra de Produtos Agrícolas" },
];
